spring:
  datasource:
    url: jdbc:mysql://10.242.2.212:3306/mysql?serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: lemon@mango
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: 10.242.2.212
    password:
    port: 6379
    timeout: 1000